version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: finance_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-net

volumes:
  postgres_data:


networks:
  finance-net:
